services:
    db:
        image: postgres:17
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: desafio
        ports:
            - "5432:5432"

