POST http://localhost:1313/courses
Content-Type: application/json

{
    "title": "Curso de javali azul"
}

###
PATCH http://localhost:1313/courses/:1
Content-Type: application/json

{
    "title": "CURSO DE COMPUTADOR"
}

###
GET http://localhost:1313/courses?orderBy=title

GET http://localhost:1313/courses/a0013003-1796-4a54-8fd5-a2e435a3eab4






Content-Type: multipart/form-data 