POST http://localhost:1313/courses
Content-Type: application/json

{
    "title": "Cur"
}

###
PATCH http://localhost:1313/courses/:1
Content-Type: application/json

{
    "title": "CURSO DE COMPUTADOR"
}

###
GET http://localhost:1313/courses

###
GET http://localhost:1313/courses/b0220e10-ab44-4b9e-af43-9ddb03c2a8e2






Content-Type: multipart/form-data 